repos:
  - repo: local
    hooks:
      # - id: pytest
      #   name: pytest (unit/integration/web tests)
      #   entry: pytest
      #   language: python
      #   types: [python]
      #   args: [tests/]
      - id: xenon
        name: xenon complexity gate (excludes legacy files)
        entry: xenon --max-absolute C --max-modules B --max-average A --exclude src/papervisor/pdf_downloader.py,src/papervisor/cli.py,src/papervisor/web_server.py src/papervisor
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        require_serial: true
      - id: radon
        name: radon maintainability/complexity summary
        entry: >
            bash -c "radon mi src/papervisor -j | python3 -c 'import sys, json; d=json.load(sys.stdin); mis=[v[\"mi\"] for v in d.values()]; grades=[v[\"rank\"] for v in d.values()]; avg_rank=chr(round(sum(map(ord,grades))/len(grades))); avg_score=sum(mis)/len(mis) if mis else 0; print(f\"Codebase average: {avg_rank} ({avg_score:.2f})\"); [print(f\"{k} - {v[\"rank\"]} ({v[\"mi\"]:.1f})\") for k,v in d.items()]'"
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
        verbose: true
  # Hygiene hooks grouped for clarity
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000', '--enforce-all']
        exclude: 'data/literature_reviews/demo_contact_center_ai/.*'
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--no-fix]  # disables formatting, lint only
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-urllib3, types-PyYAML]
        args: [--ignore-missing-imports, --no-strict-optional, --no-warn-unreachable]
