repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: clippy
        name: Rust clippy (flake8 replacement)
        args: [--all-targets, --all-features, --, -D, warnings]
        # Only run Rust clippy for Python files as a flake8 replacement
        files: \.py$
      - id: cargo-check
        name: Rust check
        files: \.rs$
    # Only run Rust hooks if Rust or Python files are present

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-urllib3]
        args: [--ignore-missing-imports, --no-strict-optional, --no-warn-unreachable]
