name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci-checks:
    name: ci-checks-(Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run ruff (pre-commit)
      run: pre-commit run ruff --all-files

    - name: Run black (pre-commit)
      run: pre-commit run black --all-files

    - name: Run mypy (pre-commit)
      run: pre-commit run mypy --all-files

    - name: Run hygiene pre-commit hooks
      run: |
        pre-commit run trailing-whitespace --all-files
        pre-commit run end-of-file-fixer --all-files
        pre-commit run check-yaml --all-files
        pre-commit run check-toml --all-files
        pre-commit run check-added-large-files --all-files
        pre-commit run check-merge-conflict --all-files
        pre-commit run debug-statements --all-files

    - name: Run pytest (pre-commit)
      run: pre-commit run pytest --all-files

    - name: Xenon complexity gate
      run: xenon --max-absolute C --max-modules B --max-average A --exclude src/papervisor/pdf_downloader.py,src/papervisor/cli.py,src/papervisor/web_server.py src/papervisor
    - name: Radon maintainability/complexity summary
      run: bash -c 'radon mi src/ | grep -E "^src/|Average" && radon cc src/ -s | grep -E "^src/|Average"'
