name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  eradicate:
    name: Eradicate (remove commented-out code)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Eradicate (remove commented-out code)
        run: eradicate src/ tests/ || true

  format:
    name: Format check with black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Format check with black
        run: black --check --diff .

  lint:
    name: Lint with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint with ruff
        run: ruff check . --no-fix

  typecheck:
    name: Type check with mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Type check with mypy
        run: mypy src/papervisor --ignore-missing-imports

  test:
    name: Test with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Test with pytest
        run: pytest tests/ -v

  xenon:
    name: Xenon complexity gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Xenon complexity gate
        run: xenon --max-absolute C --max-modules B --max-average A --exclude src/papervisor/pdf_downloader.py,src/papervisor/cli.py,src/papervisor/web_server.py src/papervisor

  radon:
    name: Radon maintainability/complexity summary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Radon maintainability/complexity summary
        run: |
          radon mi src/papervisor -j | python3 -c "import sys, json; d=json.load(sys.stdin); mis=[v['mi'] for v in d.values()]; grades=[v['rank'] for v in d.values()]; avg_rank=chr(round(sum(map(ord,grades))/len(grades))); avg_score=sum(mis)/len(mis) if mis else 0; print(f'Codebase average: {avg_rank} ({avg_score:.2f})'); [print(f'{k} - {v['rank']} ({v['mi']:.1f})') for k,v in d.items()]"

  vulture:
    name: Vulture (find unused code)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Vulture (find unused code)
        run: vulture src/ tests/ vulture_whitelist.py || true

  interrogate:
    name: Interrogate (check docstrings)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Interrogate (check docstrings)
        run: interrogate src/ tests/ --fail-under=80 || true

  bandit:
    name: Bandit (security linter)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Bandit (security linter)
        run: bandit -r src/ || true

  detect-secrets:
    name: Detect-secrets (scan for secrets)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Detect-secrets (scan for secrets)
        run: detect-secrets scan --all-files || true

  deptry:
    name: Deptry (check for unused/missing dependencies)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Deptry (check for unused/missing dependencies)
        run: deptry src/ || true

  ci-checks-python-3-12:
    name: ci-checks-(Python 3.12)
    runs-on: ubuntu-latest
    needs:
      - lint
      - format
      - typecheck
      - test
      - xenon
      - radon
      - eradicate
      - vulture
      - interrogate
      - bandit
      - detect-secrets
      - deptry
    steps:
      - name: All checks succeeded
        run: echo "All required checks passed!"
